# Generated by Django 2.0.4 on 2018-04-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hevonen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=65)),
                ('osoite', models.CharField(blank=True, max_length=225, null=True)),
                ('lempinimi', models.CharField(blank=True, max_length=65, null=True)),
                ('vh_tunnus', models.CharField(blank=True, max_length=65, null=True)),
                ('rotu', models.CharField(max_length=65)),
                ('skp', models.CharField(max_length=5)),
                ('syntaika', models.DateField(blank=True, null=True)),
                ('vari', models.CharField(blank=True, max_length=65, null=True)),
                ('saka', models.IntegerField(blank=True, null=True)),
                ('kasvattaja', models.CharField(blank=True, max_length=65, null=True)),
                ('kasvattaja_url', models.CharField(blank=True, max_length=225, null=True)),
                ('painotus', models.CharField(blank=True, max_length=25, null=True)),
                ('koulutustaso', models.CharField(blank=True, max_length=40, null=True)),
                ('nayttelyt', models.IntegerField(blank=True, null=True)),
                ('luonne', models.TextField(blank=True, null=True)),
                ('suku', models.IntegerField()),
                ('evm', models.IntegerField()),
                ('status', models.CharField(blank=True, max_length=25, null=True)),
                ('talli', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'hevonen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HevonenKuva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb', models.CharField(max_length=150)),
                ('kuva_url', models.CharField(max_length=225)),
                ('kuvaaja', models.CharField(max_length=65)),
                ('kuvaaja_url', models.CharField(blank=True, max_length=150, null=True)),
                ('lisatiedot', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'hevonen_kuva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HevonenTekstit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pvm', models.DateField()),
                ('otsikko', models.CharField(max_length=250)),
                ('teksti', models.TextField()),
                ('kirjoittaja', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'hevonen_tekstit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Meriitit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saavutus', models.CharField(max_length=10)),
                ('tilaisuus', models.CharField(blank=True, max_length=150, null=True)),
                ('pvm', models.DateField()),
                ('url', models.CharField(max_length=65)),
                ('info', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'db_table': 'meriitit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MuuKisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laji', models.CharField(max_length=15)),
                ('pvm', models.DateField()),
                ('paikka', models.CharField(max_length=50)),
                ('kutsu_url', models.CharField(max_length=65)),
                ('luokka', models.CharField(max_length=50)),
                ('sija', models.IntegerField()),
                ('osallistujia', models.IntegerField()),
                ('voittosumma', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'muu_kisa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nayttelyt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jaos', models.CharField(max_length=3)),
                ('pvm', models.DateField()),
                ('paikka', models.CharField(max_length=65)),
                ('kutsu_url', models.CharField(max_length=65)),
                ('luokka', models.CharField(max_length=65)),
                ('sija', models.CharField(max_length=10)),
                ('tulos', models.CharField(blank=True, max_length=10, null=True)),
                ('tuomari', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'nayttelyt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Omistaja',
            fields=[
                ('vrl', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nimi', models.CharField(max_length=65)),
                ('url', models.CharField(max_length=65)),
            ],
            options={
                'db_table': 'omistaja',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rotu',
            fields=[
                ('rotu', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('rotu_lyh', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'rotu',
                'managed': False,
            },
        ),
    ]
